### ISSUE TITLE
Simple question: Where to get the function ID of AWS Lambda

### ISSUE THREAD

**Issue by BaibhavVishal123** [trek10inc/aws-lambda-debugger#2]
Hi, 

I am new to Lambda. Googled a lot, but can you tell where to find the function ID which needs to be configured in "DEBUGGER_FUNCTION_ID" in launch.json.

A sample launch.json would be nice.

**Comment by azurelogic** [comment]
Hi @BaibhavVishal123,

Sorry for the ambiguity there. The `DEBUGGER_FUNCTION_ID` is a unique string of your own choosing. It's just a shared identifier between the Lambda and the URL used to connect the debugger to the broker. Think of it as a preshared key of sorts. As far as uniqueness goes, it just needs to be unique relative to any other function IDs that you (or a teammate using the same broker instance) use with other functions. Does that clear things up?

I have updated the documentation to try to make this more clear.

As for the launch.json for VS Code, I haven't had time to figure that one out myself yet. Chrome DevTools work pretty well though. If you do figure out the launch.json config, please feel free to send a PR for the README.

Thanks!

**Comment by azurelogic** [comment]
Assuming this solves it. Closing. Feel free to reopen if you still have an issue here. Thanks!
