### ISSUE TITLE
Do you think this will work with aws-serverless-express

### ISSUE THREAD

**Issue by aa3993** [trek10inc/aws-lambda-debugger#3]
Hello I use aws-serverless-express which ends with
module.exports = app
Would it work with this and how would it work?

**Comment by azurelogic** [comment]
I haven't worked with that particular package. The `require('aws-lambda-debugger')` always needs to go after any `module.exports = ...`. Whatever handler gets executed should be detected by the debugger correctly. No guarantees of course. If you do have issues using it though, please submit another issue with details. Thanks!
